PREFIX oa:     <http://www.w3.org/ns/oa#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?p ?s ?o (CONCAT("http://zoomathia.i3s.unice.fr/ExploreAWork?uri=",str(?p)) as ?url) ("fst" as ?style1) ("snd" as ?style2) WHERE {
  ?annotation2 oa:hasBody ?relationship;
        oa:hasTarget [oa:hasSource ?p;
                      oa:hasSelector [oa:exact ?mention_relationship]].

  ?relationship skos:prefLabel ?o.
  <https://opentheso.huma-num.fr/?idg=MT_25&idt=th310> skos:member ?relationship.

  ?annotation1 oa:hasBody ?animal;
               oa:hasTarget [oa:hasSource ?p;
                             oa:hasSelector [oa:exact ?mention_animal]].

  ?animal a skos:Concept; skos:prefLabel ?s.
  <https://opentheso.huma-num.fr/?idg=MT_7&idt=th310> skos:member ?animal.

  FILTER (lang(?s) = "en").
  FILTER (lang(?o) = "en")

  FILTER NOT EXISTS {
    ?animal skos:prefLabel ?s2.
    FILTER (lang(?s2) = "en")
    FILTER (
      STRLEN(?s2) < STRLEN(?s) ||
      (STRLEN(?s2) = STRLEN(?s) && LCASE(STR(?s2)) < LCASE(STR(?s))) ||
      (STRLEN(?s2) = STRLEN(?s) && LCASE(STR(?s2)) = LCASE(STR(?s)) && STR(?s2) > STR(?s))
    )
  }
  FILTER NOT EXISTS {
    ?relationship skos:prefLabel ?o2.
    FILTER (lang(?o2) = "en")
    FILTER (
      STRLEN(?o2) < STRLEN(?o) ||
      (STRLEN(?o2) = STRLEN(?o) && LCASE(STR(?o2)) < LCASE(STR(?o))) ||
      (STRLEN(?o2) = STRLEN(?o) && LCASE(STR(?o2)) = LCASE(STR(?o)) && STR(?o2) > STR(?o))
    )
  }
}
