PREFIX oa:     <http://www.w3.org/ns/oa#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
prefix zoo:     <http://www.zoomathia.com/2024/zoo#> 

SELECT DISTINCT ?p ?s ?o (?s as ?type)
  (CONCAT("http://127.0.0.1:3002/Work?uri=",str(?p)) as ?url) 
  ("fst" as ?style1) ?style2 WHERE {
  
  ?annotation2 oa:hasBody ?relation;
          oa:hasTarget [oa:hasSource ?p;
            oa:hasSelector [ oa:exact ?mention_relation]].
      ?relation skos:prefLabel ?s;
                skos:broader+ ?relation_generique.
      ?relation_generique skos:prefLabel  "special relationship"@en.
      FILTER (lang(?s) = "en")

  ?p zoo:hasAnnotation ?annotation1, ?annotation2, ?annotation3.
  
  {
      BIND("snd" as ?style2)

      ?annotation1 oa:hasBody ?animal;
              oa:hasTarget [oa:hasSource ?p;
                oa:hasSelector [oa:exact ?mention_animal]].
    ?animal a skos:Concept;
       skos:prefLabel ?o.
    ?animal_collection a skos:Collection;
       skos:prefLabel "Zoonyms"@en;
       skos:member ?animal.
    FILTER (lang(?o) = "en")

    ?annotation3 oa:hasBody ?anthro;
          oa:hasTarget [oa:hasSource ?p;
        oa:hasSelector [oa:exact ?mention_anthro]].
      ?anthro_collection skos:prefLabel "Anthroponym"@en;
                        skos:member ?anthro.
    }
    UNION{
      ?annotation3 oa:hasBody ?anthro;
          oa:hasTarget [oa:hasSource ?p;
        oa:hasSelector [oa:exact ?mention_anthro]].
      ?anthro skos:prefLabel ?o.
      ?anthro_collection skos:prefLabel "Anthroponym"@en;
                        skos:member ?anthro.
      BIND("rst" as ?style2)
      FILTER (lang(?o) = "en")

      ?annotation1 oa:hasBody ?animal;
              oa:hasTarget [oa:hasSource ?p;
                oa:hasSelector [oa:exact ?mention_animal]].
    ?animal_collection a skos:Collection;
       skos:prefLabel "Zoonyms"@en;
       skos:member ?animal.
  }
}
ORDER BY ?p