PREFIX oa:     <http://www.w3.org/ns/oa#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?p ?s ?o ("fst" as ?style1) (?s as ?date) ?type (CONCAT("http://zoomathia.i3s.unice.fr/Work?uri=", str(?p)) as ?url) ("snd" as ?style2) WHERE {
  ?annotation2 oa:hasBody ?use;
              oa:hasTarget [oa:hasSource ?p;
                            oa:hasSelector [oa:exact ?mention_use]].
                            
  ?use skos:prefLabel ?type;
	  skos:broader* <https://opentheso.huma-num.fr/?idc=105582&idt=th310>.

  ?annotation1 oa:hasBody ?animal;
              oa:hasTarget [oa:hasSource ?p;
                            oa:hasSelector [oa:exact ?mention_animal]].
  ?animal a skos:Concept;
       skos:prefLabel ?s.
  <https://opentheso.huma-num.fr/?idg=MT_7&idt=th310> skos:member ?animal.

  OPTIONAL {
    ?annotation3 oa:hasBody ?part;
    	oa:hasTarget [oa:hasSource ?p].
    ?part skos:prefLabel ?name_part.
    <https://opentheso.huma-num.fr/?idg=MT_8&idt=th310> skos:member ?part. 
    FILTER (lang(?name_part) = "en")
  }
  BIND(IF(BOUND(?name_part), ?name_part, "Unknown") AS ?o)
  FILTER(lang(?type) = "en")
}