PREFIX oa:     <http://www.w3.org/ns/oa#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema:  <http://schema.org/>

SELECT DISTINCT ?s (?length_of as ?o) ?p ?type (CONCAT("http://127.0.0.1:3002/Work?uri=",str(?p)) as ?url) ("fst" as ?style1) ("snd" as ?style2) WHERE {
  ?annotation1 oa:hasBody ?animal;
             oa:hasTarget [ oa:hasSource ?p;
                            oa:hasSelector [ oa:exact ?mention_animal]].
  ?animal skos:prefLabel ?s.
  ?animal_collection a skos:Collection;
       skos:prefLabel "Zoonyms"@en;
       skos:member ?animal.

  ?annotation2 oa:hasBody ?pregnancy;
               oa:hasTarget [oa:hasSource ?p;
                             oa:hasSelector [ oa:exact ?mention_pregnancy]].
  ?pregnancy skos:prefLabel ?length_of;
    skos:broader/skos:broader ?type_g.
  ?type_g skos:prefLabel ?type. 
  filter(?length_of in ("length of incubation"@en, "length of pregnancy"@en))
  FILTER (lang(?s) = "en")
  filter (lang(?type) ="en")
}