version: "3.9"

services:
  web-backend:
    image: zoomathia/backend
    container_name: backend
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3001:3001
  corese:
    image: wimmics/corese
    build: ./corese
    ports:
      - "8080:8080"
    volumes:
      - "/home/abarbe/Corese/Zoomathia/:/usr/local/corese/data"
    environment:
      JVM_XMX: "16G"
